const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Exps.FaceSize,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.JavaScriptInEvents.EventSheet1_Event18_Act3,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.JavaScriptInEvents.EventSheet1_Event22_Act1,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y
	];
};
self.C3_JsPropNameTable = [
	{NodeID: 0},
	{spr_node_1: 0},
	{spr_node_2: 0},
	{spr_node_3: 0},
	{spr_node_4: 0},
	{nodeID: 0},
	{spr_spwn_node: 0},
	{Touch: 0},
	{Audio: 0},
	{type: 0},
	{animationFrameNo: 0},
	{spr_player_0: 0},
	{spr_player_1: 0},
	{spr_player_2: 0},
	{spr_player_3: 0},
	{spr_ui3: 0},
	{MoveTo: 0},
	{Tween: 0},
	{spr_enemy: 0},
	{txt_score: 0},
	{HUD_sound: 0},
	{HUD_back: 0},
	{Hand: 0},
	{Mouse: 0},
	{Solid: 0},
	{PlayerFamily: 0},
	{TargetNodeFamily: 0},
	{Score: 0},
	{Spwn_Enemy_Timmer: 0},
	{Next_Milestone: 0},
	{gameOver: 0},
	{isSound: 0}
];

self.InstanceType = {
	spr_node_1: class extends self.ISpriteInstance {},
	spr_node_2: class extends self.ISpriteInstance {},
	spr_node_3: class extends self.ISpriteInstance {},
	spr_node_4: class extends self.ISpriteInstance {},
	spr_spwn_node: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	spr_player_0: class extends self.ISpriteInstance {},
	spr_player_1: class extends self.ISpriteInstance {},
	spr_player_2: class extends self.ISpriteInstance {},
	spr_player_3: class extends self.ISpriteInstance {},
	spr_ui3: class extends self.ISpriteInstance {},
	spr_enemy: class extends self.ISpriteInstance {},
	txt_score: class extends self.ITextInstance {},
	HUD_sound: class extends self.ISpriteInstance {},
	HUD_back: class extends self.ISpriteInstance {},
	Hand: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	PlayerFamily: class extends self.ISpriteInstance {},
	TargetNodeFamily: class extends self.ISpriteInstance {}
}