const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Timeline,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Arr,
		C3.Behaviors.Physics,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.JavaScriptInEvents.E_game_Event13_Act2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.JavaScriptInEvents.E_game_Event41_Act1,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetX
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Touch: 0},
	{Keyboard: 0},
	{TimelineController: 0},
	{Browser: 0},
	{spr_spwn_1: 0},
	{spr_spwn_2: 0},
	{spr_spwn_3: 0},
	{spr_spwn_4: 0},
	{spr_spwn_5: 0},
	{spr_spwn_6: 0},
	{spr_spwn_7: 0},
	{spr_spwn_8: 0},
	{hasTile: 0},
	{selceted_latter: 0},
	{spr_spwn_9: 0},
	{spr_spwn_10: 0},
	{spr_spwn_11: 0},
	{spr_spwn_12: 0},
	{spr_spwn_13: 0},
	{spr_spwn_14: 0},
	{id: 0},
	{select_spwn: 0},
	{partical_1: 0},
	{partical_2: 0},
	{partical_3: 0},
	{partical_4: 0},
	{Tween: 0},
	{Flash: 0},
	{selectedTitle: 0},
	{isClicked: 0},
	{isGameOver: 0},
	{Solid: 0},
	{Platform: 0},
	{tiles: 0},
	{buttons: 0},
	{ok: 0},
	{play_again: 0},
	{back_btn: 0},
	{isCounting: 0},
	{OrbCount: 0},
	{score: 0},
	{send_btn: 0},
	{message_text: 0},
	{game_over_text: 0},
	{play_again_btn: 0},
	{moveX: 0},
	{moveY: 0},
	{alphabets: 0},
	{background: 0},
	{extra: 0},
	{loadingBar: 0},
	{message: 0},
	{score_board: 0},
	{showScore: 0},
	{side_border_1: 0},
	{side_border_2: 0},
	{Bullet: 0},
	{spr_ball: 0},
	{game_over_spr: 0},
	{cursor: 0},
	{CreateTiles: 0},
	{ErrorMessages: 0},
	{Family_Physics: 0},
	{Particals: 0},
	{isClickedTile: 0},
	{customX: 0},
	{sendTileToSelectedPositionTime: 0},
	{int_to_world: 0},
	{isItRealWorld: 0},
	{WordList: 0},
	{count_score: 0},
	{min_latter_selected: 0},
	{gameOver: 0},
	{slotIndex: 0},
	{randomNumber: 0},
	{char_number: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	spr_spwn_1: class extends self.ISpriteInstance {},
	spr_spwn_2: class extends self.ISpriteInstance {},
	spr_spwn_3: class extends self.ISpriteInstance {},
	spr_spwn_4: class extends self.ISpriteInstance {},
	spr_spwn_5: class extends self.ISpriteInstance {},
	spr_spwn_6: class extends self.ISpriteInstance {},
	spr_spwn_7: class extends self.ISpriteInstance {},
	spr_spwn_8: class extends self.ISpriteInstance {},
	spr_spwn_9: class extends self.ISpriteInstance {},
	spr_spwn_10: class extends self.ISpriteInstance {},
	spr_spwn_11: class extends self.ISpriteInstance {},
	spr_spwn_12: class extends self.ISpriteInstance {},
	spr_spwn_13: class extends self.ISpriteInstance {},
	spr_spwn_14: class extends self.ISpriteInstance {},
	select_spwn: class extends self.ISpriteInstance {},
	partical_1: class extends self.ISpriteInstance {},
	partical_2: class extends self.ISpriteInstance {},
	partical_3: class extends self.ISpriteInstance {},
	partical_4: class extends self.ISpriteInstance {},
	selectedTitle: class extends self.ISpriteInstance {},
	tiles: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	ok: class extends self.ISpriteInstance {},
	play_again: class extends self.ISpriteInstance {},
	back_btn: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	send_btn: class extends self.ITextInstance {},
	message_text: class extends self.ITextInstance {},
	game_over_text: class extends self.ITextInstance {},
	play_again_btn: class extends self.ITextInstance {},
	alphabets: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	extra: class extends self.ISpriteInstance {},
	loadingBar: class extends self.ISpriteInstance {},
	message: class extends self.ISpriteInstance {},
	score_board: class extends self.ISpriteInstance {},
	showScore: class extends self.ISpriteInstance {},
	side_border_1: class extends self.ISpriteInstance {},
	side_border_2: class extends self.ISpriteInstance {},
	spr_ball: class extends self.ISpriteInstance {},
	game_over_spr: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	CreateTiles: class extends self.IArrayInstance {},
	ErrorMessages: class extends self.IArrayInstance {},
	Particals: class extends self.ISpriteInstance {}
}