const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Behaviors.Turret,
		C3.Behaviors.Pin,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.ScriptsInEvents.E_game_1_Event19_Act2,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{DestroyOutsideLayout: 0},
	{Bullet: 0},
	{Arrow_1: 0},
	{torrent: 0},
	{Turret: 0},
	{Pin: 0},
	{torrent_1: 0},
	{health: 0},
	{PathIndex: 0},
	{Pathfinding: 0},
	{Flash: 0},
	{Enemy_1___: 0},
	{Enemy_2: 0},
	{Enemy_Ants: 0},
	{Health: 0},
	{Enemy_1: 0},
	{Enemy_Target: 0},
	{EnemySpawner: 0},
	{Solid: 0},
	{spr_no_access: 0},
	{Enemy_4: 0},
	{Enemy_Spawn_Effect: 0},
	{node_2_0: 0},
	{node_2_1: 0},
	{node_2_10: 0},
	{node_2_11: 0},
	{node_2_12: 0},
	{node_2_13: 0},
	{node_2_14: 0},
	{node_2_15: 0},
	{node_2_16: 0},
	{node_2_17: 0},
	{node_2_18: 0},
	{node_2_19: 0},
	{node_2_2: 0},
	{node_2_20: 0},
	{node_2_21: 0},
	{node_2_22: 0},
	{node_2_23: 0},
	{node_2_24: 0},
	{node_2_3: 0},
	{node_2_4: 0},
	{node_2_5: 0},
	{node_2_6: 0},
	{node_2_7: 0},
	{node_2_8: 0},
	{node_2_9: 0},
	{node_1_0: 0},
	{node_1_1: 0},
	{node_1_2: 0},
	{node_1_3: 0},
	{node_1_4: 0},
	{node_1_5: 0},
	{node_1_6: 0},
	{node_1_7: 0},
	{node_1_8: 0},
	{node_1_9: 0},
	{node_1_10: 0},
	{bg: 0},
	{bg_decoration: 0},
	{animated_water: 0},
	{water: 0},
	{show_score: 0},
	{Bridge: 0},
	{pathArray_2: 0},
	{pathArray_1_1: 0},
	{pathArray_1_2: 0},
	{Audio: 0},
	{Browser: 0},
	{score: 0},
	{Score: 0},
	{Touch: 0},
	{build_tower: 0},
	{spr_builder: 0},
	{Builder_House: 0},
	{spr_build_effect: 0},
	{spr_Shadow: 0},
	{Player_Tower: 0},
	{FullScreen: 0},
	{Fire: 0},
	{Main_Helth: 0},
	{Enmey_Health: 0},
	{CursorSprite: 0},
	{Mouse: 0},
	{Explosions: 0},
	{anemy_movment_speed: 0},
	{Count_Score: 0},
	{Count_Main_health: 0},
	{isFullScreen: 0},
	{anemy_movment_speed2: 0},
	{Count_Score2: 0}
];

self.InstanceType = {
	Arrow_1: class extends self.ISpriteInstance {},
	torrent: class extends self.ISpriteInstance {},
	torrent_1: class extends self.ISpriteInstance {},
	Enemy_1___: class extends self.ISpriteInstance {},
	Enemy_2: class extends self.ISpriteInstance {},
	Enemy_Ants: class extends self.ISpriteInstance {},
	Enemy_1: class extends self.ISpriteInstance {},
	Enemy_Target: class extends self.ISpriteInstance {},
	EnemySpawner: class extends self.ISpriteInstance {},
	spr_no_access: class extends self.ISpriteInstance {},
	Enemy_4: class extends self.ISpriteInstance {},
	Enemy_Spawn_Effect: class extends self.ISpriteInstance {},
	node_2_0: class extends self.ISpriteInstance {},
	node_2_1: class extends self.ISpriteInstance {},
	node_2_10: class extends self.ISpriteInstance {},
	node_2_11: class extends self.ISpriteInstance {},
	node_2_12: class extends self.ISpriteInstance {},
	node_2_13: class extends self.ISpriteInstance {},
	node_2_14: class extends self.ISpriteInstance {},
	node_2_15: class extends self.ISpriteInstance {},
	node_2_16: class extends self.ISpriteInstance {},
	node_2_17: class extends self.ISpriteInstance {},
	node_2_18: class extends self.ISpriteInstance {},
	node_2_19: class extends self.ISpriteInstance {},
	node_2_2: class extends self.ISpriteInstance {},
	node_2_20: class extends self.ISpriteInstance {},
	node_2_21: class extends self.ISpriteInstance {},
	node_2_22: class extends self.ISpriteInstance {},
	node_2_23: class extends self.ISpriteInstance {},
	node_2_24: class extends self.ISpriteInstance {},
	node_2_3: class extends self.ISpriteInstance {},
	node_2_4: class extends self.ISpriteInstance {},
	node_2_5: class extends self.ISpriteInstance {},
	node_2_6: class extends self.ISpriteInstance {},
	node_2_7: class extends self.ISpriteInstance {},
	node_2_8: class extends self.ISpriteInstance {},
	node_2_9: class extends self.ISpriteInstance {},
	node_1_0: class extends self.ISpriteInstance {},
	node_1_1: class extends self.ISpriteInstance {},
	node_1_2: class extends self.ISpriteInstance {},
	node_1_3: class extends self.ISpriteInstance {},
	node_1_4: class extends self.ISpriteInstance {},
	node_1_5: class extends self.ISpriteInstance {},
	node_1_6: class extends self.ISpriteInstance {},
	node_1_7: class extends self.ISpriteInstance {},
	node_1_8: class extends self.ISpriteInstance {},
	node_1_9: class extends self.ISpriteInstance {},
	node_1_10: class extends self.ISpriteInstance {},
	bg: class extends self.ITilemapInstance {},
	bg_decoration: class extends self.ITilemapInstance {},
	animated_water: class extends self.ISpriteInstance {},
	water: class extends self.ITilemapInstance {},
	show_score: class extends self.ISpriteInstance {},
	Bridge: class extends self.ITilemapInstance {},
	pathArray_2: class extends self.IArrayInstance {},
	pathArray_1_1: class extends self.IArrayInstance {},
	pathArray_1_2: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Score: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	build_tower: class extends self.ISpriteInstance {},
	spr_builder: class extends self.ISpriteInstance {},
	Builder_House: class extends self.ISpriteInstance {},
	spr_build_effect: class extends self.ISpriteInstance {},
	spr_Shadow: class extends self.ISpriteInstance {},
	Player_Tower: class extends self.ISpriteInstance {},
	FullScreen: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	Main_Helth: class extends self.ITextInstance {},
	Enmey_Health: class extends self.ISpriteInstance {},
	CursorSprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Explosions: class extends self.ISpriteInstance {}
}