const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Turret,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Particles,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.Timeline,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Turret.Acts.ClearTargets,
		C3.Behaviors.Turret.Acts.SetRange,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.ScriptsInEvents.E_game_1_Event60_Act2,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{DestroyOutsideLayout: 0},
	{Bullet: 0},
	{Arrow_1: 0},
	{is_click: 0},
	{DragDrop: 0},
	{torrent: 0},
	{isRangeActive: 0},
	{Turret: 0},
	{torrent_1: 0},
	{spr_turrent_1_range: 0},
	{health: 0},
	{body_1: 0},
	{isFire: 0},
	{head_1: 0},
	{health_container_1: 0},
	{health_bar_1: 0},
	{isActive: 0},
	{MoveTo: 0},
	{update_turrent: 0},
	{build_tower: 0},
	{spr_boom: 0},
	{hasBoat: 0},
	{spr_boat_stop_1: 0},
	{spr_boat_stop_2: 0},
	{spr_path_boat_1: 0},
	{spr_path_boat_2: 0},
	{spr_path_boat_target: 0},
	{PathIndex: 0},
	{Pathfinding: 0},
	{spr_boat_1: 0},
	{spr_boat_cannon_1: 0},
	{spr_create_boat: 0},
	{EnemyContainer: 0},
	{Health: 0},
	{selectPath: 0},
	{L1_Enemy_1: 0},
	{spr_foot_print_1: 0},
	{L1_Enemy_2: 0},
	{spr_foot_print_2: 0},
	{Enemy_3: 0},
	{spr_cannon_3: 0},
	{spr_enemy_3_area: 0},
	{Enemy_4: 0},
	{spr_range_4: 0},
	{Enemy_Target: 0},
	{EnemySpawner: 0},
	{Solid: 0},
	{spr_no_access: 0},
	{Enemy_Spawn_Effect: 0},
	{node_1_0: 0},
	{node_1_1: 0},
	{node_1_2: 0},
	{node_1_3: 0},
	{node_1_4: 0},
	{node_1_5: 0},
	{node_1_6: 0},
	{node_1_7: 0},
	{node_1_8: 0},
	{node_1_9: 0},
	{node_1_10: 0},
	{node_1_11: 0},
	{node_1_12: 0},
	{node_1_13: 0},
	{node_1_14: 0},
	{node_1_15: 0},
	{node_1_16: 0},
	{node_1_17: 0},
	{node_1_18: 0},
	{node_1_19: 0},
	{node_1_20: 0},
	{node_1_21: 0},
	{node_1_22: 0},
	{node_1_23: 0},
	{path_detected: 0},
	{starting_bg: 0},
	{spr_game_title_loading: 0},
	{spr_loading_title: 0},
	{spr_bg_title_screan_loading: 0},
	{spr_loading_up_deco: 0},
	{spr_deco_round: 0},
	{spr_play_btn: 0},
	{bg: 0},
	{bg_decoration: 0},
	{animated_water: 0},
	{water: 0},
	{show_score: 0},
	{Bridge: 0},
	{spr_road_bridge: 0},
	{pathArray_1_to_2: 0},
	{pathArray_1_1: 0},
	{pathArray_1_2: 0},
	{pathArray_2_to_1: 0},
	{Wave_Enemy: 0},
	{pathWaterDown: 0},
	{Audio: 0},
	{Browser: 0},
	{ScoreText: 0},
	{Touch: 0},
	{Mouse: 0},
	{spr_builder: 0},
	{Builder_House: 0},
	{spr_build_effect: 0},
	{spr_Shadow: 0},
	{spr_stay_builder: 0},
	{CursorSprite: 0},
	{Full: 0},
	{Exit: 0},
	{coinCollectText: 0},
	{Explosions: 0},
	{Fire: 0},
	{spr_coin: 0},
	{spr_coin_spwan: 0},
	{spr_coin_text: 0},
	{spr_reload: 0},
	{spr_score_icon: 0},
	{Sine: 0},
	{spr_shadow_game_over: 0},
	{spr_spwan_2: 0},
	{spr_tanel: 0},
	{spr_spell: 0},
	{fontCoin: 0},
	{fontScore: 0},
	{isCenter: 0},
	{Flash: 0},
	{wave: 0},
	{message: 0},
	{tapToPlay: 0},
	{gameOver: 0},
	{fontShowCoin: 0},
	{fontWave: 0},
	{fontWaveCount: 0},
	{fontRemainingEnemy: 0},
	{fontLoading: 0},
	{spr_show_wave_end: 0},
	{spr_show_wave_start: 0},
	{spr_show_wave_stay: 0},
	{spr_enemy_fire: 0},
	{spr_turrent_fire: 0},
	{spr_enemy_car_fire: 0},
	{spr_main_tower_fire: 0},
	{spr_boat_fire: 0},
	{fire_1: 0},
	{Main_Helth: 0},
	{Player_Tower: 0},
	{spr_stop_enemy_range: 0},
	{spr_fire_home_tower_range: 0},
	{spr_cannon: 0},
	{health_bar_home: 0},
	{health_container_home: 0},
	{spr_bridge_1: 0},
	{spr_bridge_2: 0},
	{spr_bridge_3_up: 0},
	{spr_bridge_3_down: 0},
	{WaveTimeLine: 0},
	{anemy_movment_speed: 0},
	{Count_Main_health: 0},
	{isFullScreen: 0},
	{showMessage: 0},
	{isGameOver: 0},
	{selectPath2: 0},
	{isCreateEnemy: 0},
	{isPath_1_to_2: 0},
	{isPath_2_to_1: 0},
	{isPath_2_to_2: 0},
	{boat_count: 0},
	{waterAttact: 0},
	{destroyEnemy: 0},
	{wave_count: 0},
	{Collect_Coin: 0},
	{isLoadingScreen: 0},
	{Count_Score: 0},
	{X: 0},
	{Y: 0},
	{SCORE: 0},
	{COIN: 0},
	{DESTORY: 0}
];

self.InstanceType = {
	Arrow_1: class extends self.ISpriteInstance {},
	torrent: class extends self.ISpriteInstance {},
	torrent_1: class extends self.ISpriteInstance {},
	spr_turrent_1_range: class extends self.ISpriteInstance {},
	body_1: class extends self.ISpriteInstance {},
	head_1: class extends self.ISpriteInstance {},
	health_container_1: class extends self.ISpriteInstance {},
	health_bar_1: class extends self.ISpriteInstance {},
	update_turrent: class extends self.ISpriteInstance {},
	build_tower: class extends self.ISpriteInstance {},
	spr_boom: class extends self.ISpriteInstance {},
	spr_boat_stop_1: class extends self.ISpriteInstance {},
	spr_boat_stop_2: class extends self.ISpriteInstance {},
	spr_path_boat_1: class extends self.ISpriteInstance {},
	spr_path_boat_2: class extends self.ISpriteInstance {},
	spr_path_boat_target: class extends self.ISpriteInstance {},
	spr_boat_1: class extends self.ISpriteInstance {},
	spr_boat_cannon_1: class extends self.ISpriteInstance {},
	spr_create_boat: class extends self.ISpriteInstance {},
	EnemyContainer: class extends self.ISpriteInstance {},
	L1_Enemy_1: class extends self.ISpriteInstance {},
	spr_foot_print_1: class extends self.IParticlesInstance {},
	L1_Enemy_2: class extends self.ISpriteInstance {},
	spr_foot_print_2: class extends self.IParticlesInstance {},
	Enemy_3: class extends self.ISpriteInstance {},
	spr_cannon_3: class extends self.ISpriteInstance {},
	spr_enemy_3_area: class extends self.ISpriteInstance {},
	Enemy_4: class extends self.ISpriteInstance {},
	spr_range_4: class extends self.ISpriteInstance {},
	Enemy_Target: class extends self.ISpriteInstance {},
	EnemySpawner: class extends self.ISpriteInstance {},
	spr_no_access: class extends self.ISpriteInstance {},
	Enemy_Spawn_Effect: class extends self.ISpriteInstance {},
	node_1_0: class extends self.ISpriteInstance {},
	node_1_1: class extends self.ISpriteInstance {},
	node_1_2: class extends self.ISpriteInstance {},
	node_1_3: class extends self.ISpriteInstance {},
	node_1_4: class extends self.ISpriteInstance {},
	node_1_5: class extends self.ISpriteInstance {},
	node_1_6: class extends self.ISpriteInstance {},
	node_1_7: class extends self.ISpriteInstance {},
	node_1_8: class extends self.ISpriteInstance {},
	node_1_9: class extends self.ISpriteInstance {},
	node_1_10: class extends self.ISpriteInstance {},
	node_1_11: class extends self.ISpriteInstance {},
	node_1_12: class extends self.ISpriteInstance {},
	node_1_13: class extends self.ISpriteInstance {},
	node_1_14: class extends self.ISpriteInstance {},
	node_1_15: class extends self.ISpriteInstance {},
	node_1_16: class extends self.ISpriteInstance {},
	node_1_17: class extends self.ISpriteInstance {},
	node_1_18: class extends self.ISpriteInstance {},
	node_1_19: class extends self.ISpriteInstance {},
	node_1_20: class extends self.ISpriteInstance {},
	node_1_21: class extends self.ISpriteInstance {},
	node_1_22: class extends self.ISpriteInstance {},
	node_1_23: class extends self.ISpriteInstance {},
	path_detected: class extends self.ISpriteInstance {},
	starting_bg: class extends self.ITilemapInstance {},
	spr_game_title_loading: class extends self.ISpriteInstance {},
	spr_loading_title: class extends self.ITextInstance {},
	spr_bg_title_screan_loading: class extends self.ISpriteInstance {},
	spr_loading_up_deco: class extends self.ISpriteInstance {},
	spr_deco_round: class extends self.ISpriteInstance {},
	spr_play_btn: class extends self.ISpriteInstance {},
	bg: class extends self.ITilemapInstance {},
	bg_decoration: class extends self.ITilemapInstance {},
	animated_water: class extends self.ISpriteInstance {},
	water: class extends self.ITilemapInstance {},
	show_score: class extends self.ISpriteInstance {},
	Bridge: class extends self.ITilemapInstance {},
	spr_road_bridge: class extends self.ISpriteInstance {},
	pathArray_1_to_2: class extends self.IArrayInstance {},
	pathArray_1_1: class extends self.IArrayInstance {},
	pathArray_1_2: class extends self.IArrayInstance {},
	pathArray_2_to_1: class extends self.IArrayInstance {},
	Wave_Enemy: class extends self.IArrayInstance {},
	pathWaterDown: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ScoreText: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	spr_builder: class extends self.ISpriteInstance {},
	Builder_House: class extends self.ISpriteInstance {},
	spr_build_effect: class extends self.ISpriteInstance {},
	spr_Shadow: class extends self.ISpriteInstance {},
	spr_stay_builder: class extends self.ISpriteInstance {},
	CursorSprite: class extends self.ISpriteInstance {},
	Full: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {},
	coinCollectText: class extends self.ITextInstance {},
	Explosions: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	spr_coin: class extends self.ISpriteInstance {},
	spr_coin_spwan: class extends self.ISpriteInstance {},
	spr_coin_text: class extends self.ITextInstance {},
	spr_reload: class extends self.ISpriteInstance {},
	spr_score_icon: class extends self.ISpriteInstance {},
	spr_shadow_game_over: class extends self.ISpriteInstance {},
	spr_spwan_2: class extends self.ISpriteInstance {},
	spr_tanel: class extends self.ISpriteInstance {},
	spr_spell: class extends self.ISpriteInstance {},
	fontCoin: class extends self.ISpriteFontInstance {},
	fontScore: class extends self.ISpriteFontInstance {},
	wave: class extends self.ISpriteFontInstance {},
	message: class extends self.ISpriteFontInstance {},
	tapToPlay: class extends self.ISpriteFontInstance {},
	gameOver: class extends self.ISpriteFontInstance {},
	fontShowCoin: class extends self.ISpriteFontInstance {},
	fontWave: class extends self.ISpriteFontInstance {},
	fontWaveCount: class extends self.ISpriteFontInstance {},
	fontRemainingEnemy: class extends self.ISpriteFontInstance {},
	fontLoading: class extends self.ISpriteFontInstance {},
	spr_show_wave_end: class extends self.ISpriteInstance {},
	spr_show_wave_start: class extends self.ISpriteInstance {},
	spr_show_wave_stay: class extends self.ISpriteInstance {},
	spr_enemy_fire: class extends self.ISpriteInstance {},
	spr_turrent_fire: class extends self.ISpriteInstance {},
	spr_enemy_car_fire: class extends self.ISpriteInstance {},
	spr_main_tower_fire: class extends self.ISpriteInstance {},
	spr_boat_fire: class extends self.ISpriteInstance {},
	fire_1: class extends self.ISpriteInstance {},
	Main_Helth: class extends self.ITextInstance {},
	Player_Tower: class extends self.ISpriteInstance {},
	spr_stop_enemy_range: class extends self.ISpriteInstance {},
	spr_fire_home_tower_range: class extends self.ISpriteInstance {},
	spr_cannon: class extends self.ISpriteInstance {},
	health_bar_home: class extends self.ISpriteInstance {},
	health_container_home: class extends self.ISpriteInstance {},
	spr_bridge_1: class extends self.ISpriteInstance {},
	spr_bridge_2: class extends self.ISpriteInstance {},
	spr_bridge_3_up: class extends self.ISpriteInstance {},
	spr_bridge_3_down: class extends self.ISpriteInstance {},
	WaveTimeLine: class extends self.IInstance {}
}