const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Exps.unixtime,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.E_game_Event7_Act6,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Touch: 0},
	{spr_extra_point_text: 0},
	{spr_score_text: 0},
	{Bullet: 0},
	{spr_ball: 0},
	{spr_ball_destroy: 0},
	{MoveTo: 0},
	{spr_extra_ball: 0},
	{spr_play_btn: 0},
	{spr_mute_btn: 0},
	{spr_btn_left: 0},
	{spr_btn_right: 0},
	{spr_ui: 0},
	{bg: 0},
	{spr_round: 0},
	{angle_no: 0},
	{speed: 0},
	{Solid: 0},
	{spr_player: 0},
	{spr_score_container: 0},
	{spr_bg_light: 0},
	{spr_spwn_extra_ball: 0},
	{spr_game_title: 0},
	{spr_slug: 0},
	{Tween: 0},
	{spr_game_over: 0},
	{spr_bg_text_score: 0},
	{Audio: 0},
	{OrbitAngle: 0},
	{Radius: 0},
	{player_move_speed: 0},
	{Score: 0},
	{isGameOver: 0},
	{TotalClicks: 0},
	{GameStartTime: 0},
	{randomPoint: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	spr_extra_point_text: class extends self.ITextInstance {},
	spr_score_text: class extends self.ITextInstance {},
	spr_ball: class extends self.ISpriteInstance {},
	spr_ball_destroy: class extends self.ISpriteInstance {},
	spr_extra_ball: class extends self.ISpriteInstance {},
	spr_play_btn: class extends self.ISpriteInstance {},
	spr_mute_btn: class extends self.ISpriteInstance {},
	spr_btn_left: class extends self.ISpriteInstance {},
	spr_btn_right: class extends self.ISpriteInstance {},
	spr_ui: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	spr_round: class extends self.ISpriteInstance {},
	spr_player: class extends self.ISpriteInstance {},
	spr_score_container: class extends self.ISpriteInstance {},
	spr_bg_light: class extends self.ISpriteInstance {},
	spr_spwn_extra_ball: class extends self.ISpriteInstance {},
	spr_game_title: class extends self.ISpriteInstance {},
	spr_slug: class extends self.ISpriteInstance {},
	spr_game_over: class extends self.ISpriteInstance {},
	spr_bg_text_score: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}