const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{spr_not_allow: 0},
	{isPlayer: 0},
	{spr_goal_count: 0},
	{spr_goal_win_loss_node: 0},
	{Sine: 0},
	{start_btn: 0},
	{level: 0},
	{star_count: 0},
	{Tween: 0},
	{ShadowCaster: 0},
	{level_selection: 0},
	{level_selection_title: 0},
	{level_selection_star: 0},
	{id: 0},
	{start_level_count: 0},
	{level_selection_next_prev: 0},
	{Keyboard: 0},
	{Touch: 0},
	{spr_start: 0},
	{DestroyOutside: 0},
	{spr_goal_win_loss: 0},
	{text_level_selection: 0},
	{select_number: 0},
	{text_score_computer: 0},
	{text_score_player: 0},
	{bg: 0},
	{UI_demo: 0},
	{spr_sidebar: 0},
	{"8Direction": 0},
	{spr_player: 0},
	{spr_ui: 0},
	{goal_target: 0},
	{Bullet: 0},
	{spr_ball: 0},
	{spr_ball_hit: 0},
	{court_center_line: 0},
	{spr_celebration: 0},
	{spr_start_ball: 0},
	{spr_level_select_ball: 0},
	{Mouse: 0},
	{MoveTo: 0},
	{spr_computer: 0},
	{game_title: 0},
	{spr_game_title: 0},
	{beforeBallSpeed: 0},
	{isPlay: 0},
	{computer_score: 0},
	{player_score: 0},
	{score: 0},
	{level_start_in_page: 0}
];

self.InstanceType = {
	spr_not_allow: class extends self.ISpriteInstance {},
	spr_goal_count: class extends self.ISpriteInstance {},
	spr_goal_win_loss_node: class extends self.ISpriteInstance {},
	start_btn: class extends self.ISpriteInstance {},
	level_selection: class extends self.ISpriteInstance {},
	level_selection_title: class extends self.ISpriteInstance {},
	level_selection_star: class extends self.ISpriteInstance {},
	level_selection_next_prev: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	spr_start: class extends self.ISpriteInstance {},
	spr_goal_win_loss: class extends self.ISpriteInstance {},
	text_level_selection: class extends self.ITextInstance {},
	select_number: class extends self.ITextInstance {},
	text_score_computer: class extends self.ITextInstance {},
	text_score_player: class extends self.ITextInstance {},
	bg: class extends self.ISpriteInstance {},
	UI_demo: class extends self.ISpriteInstance {},
	spr_sidebar: class extends self.ISpriteInstance {},
	spr_player: class extends self.ISpriteInstance {},
	spr_ui: class extends self.ISpriteInstance {},
	spr_ball: class extends self.ISpriteInstance {},
	spr_ball_hit: class extends self.ISpriteInstance {},
	court_center_line: class extends self.ISpriteInstance {},
	spr_celebration: class extends self.ISpriteInstance {},
	spr_start_ball: class extends self.ISpriteInstance {},
	spr_level_select_ball: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	spr_computer: class extends self.ISpriteInstance {},
	game_title: class extends self.ISpriteInstance {},
	spr_game_title: class extends self.ISpriteInstance {}
}