{
	"version": 1502786633,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/pinggiran-sheet0.png",
		"images/bola-sheet0.png",
		"images/gawang-sheet0.png",
		"images/tiledbackground.png",
		"images/masukgol-sheet0.png",
		"images/bomb-sheet0.png",
		"images/bomb-sheet1.png",
		"images/bomb_explode-sheet0.png",
		"images/live-sheet0.png",
		"images/live-sheet1.png",
		"images/score_board-sheet0.png",
		"images/play_btn-sheet0.png",
		"images/title-sheet0.png",
		"images/goal-sheet0.png",
		"images/result-sheet0.png",
		"images/home-sheet0.png",
		"images/replay-sheet0.png",
		"images/pause_play-sheet0.png",
		"images/pause_play-sheet1.png",
		"images/mute_sound-sheet0.png",
		"images/mute_sound-sheet1.png",
		"images/setting-sheet0.png",
		"images/backtoweb-sheet0.png",
		"media/bgm.m4a",
		"media/bgm.ogg",
		"media/bump3.m4a",
		"media/bump3.ogg",
		"media/explosion 2.m4a",
		"media/explosion 2.ogg",
		"media/hit3.m4a",
		"media/hit3.ogg",
		"media/ok - 1.m4a",
		"media/ok - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"txtgameid.txt"
	]
}