const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{health: 0},
	{enemy_1: 0},
	{enemy_spawnr: 0},
	{Keyboard: 0},
	{Solid: 0},
	{no_entry: 0},
	{"8Direction": 0},
	{Flash: 0},
	{player_base_1: 0},
	{Bullet: 0},
	{player_bullate_1: 0},
	{main_bg: 0},
	{bg_1: 0},
	{bg_2: 0},
	{bg_3: 0},
	{bullet_gain: 0},
	{Bullet2: 0},
	{Enemy: 0},
	{Bonus: 0},
	{Player: 0},
	{enemy_count: 0},
	{rate_of_fire: 0},
	{isCreateEnemy: 0},
	{player_shoot_count: 0},
	{score: 0},
	{count: 0}
];

self.InstanceType = {
	enemy_1: class extends self.ISpriteInstance {},
	enemy_spawnr: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	no_entry: class extends self.ISpriteInstance {},
	player_base_1: class extends self.ISpriteInstance {},
	player_bullate_1: class extends self.ISpriteInstance {},
	main_bg: class extends self.ITiledBackgroundInstance {},
	bg_1: class extends self.ISpriteInstance {},
	bg_2: class extends self.ISpriteInstance {},
	bg_3: class extends self.ISpriteInstance {},
	bullet_gain: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Bonus: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {}
}