const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Behaviors.Rotate,
		C3.Behaviors.destroy,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.JavaScriptInEvents.E_game_Event2_Act5,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.JavaScriptInEvents.E_game_Event22_Act2,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Exps.int
	];
};
self.C3_JsPropNameTable = [
	{spr_active_ball_node: 0},
	{Physics: 0},
	{spr_hole_node: 0},
	{spr_no_access: 0},
	{activeBallWall: 0},
	{spr_start_ball_pos: 0},
	{spr_node_ball_send: 0},
	{spr_node_type_cng: 0},
	{spr_ball_node_sound: 0},
	{spr_ball_count_text: 0},
	{spr_score_text: 0},
	{Tween: 0},
	{spr_game_over_text: 0},
	{spr_game_over_score_text: 0},
	{spr_back_btn: 0},
	{btn_sound: 0},
	{spr_reload_btn: 0},
	{BG: 0},
	{spr_ball_container: 0},
	{spr_ball_container2: 0},
	{Touch: 0},
	{id: 0},
	{spr_door_bar: 0},
	{hasScore: 0},
	{Rotate: 0},
	{DestroyOutside: 0},
	{MoveTo: 0},
	{spr_ball: 0},
	{spr_hole_container: 0},
	{Pin: 0},
	{spr_holes: 0},
	{spr_glass: 0},
	{spr_air_flow: 0},
	{tapToPlay: 0},
	{spr_ball_ramin: 0},
	{spr_node_game_over: 0},
	{Audio: 0},
	{spr_node_ball_shake: 0},
	{isStartGame: 0},
	{totalBall: 0},
	{PrevBallCount: 0},
	{DestroyedBall: 0},
	{picIndex: 0},
	{SCORE: 0},
	{isSound: 0},
	{holeContainerRotated: 0},
	{counter: 0},
	{ballDestroyCounter: 0},
	{ballDropCounter: 0}
];

self.InstanceType = {
	spr_active_ball_node: class extends self.ISpriteInstance {},
	spr_hole_node: class extends self.ISpriteInstance {},
	spr_no_access: class extends self.ISpriteInstance {},
	activeBallWall: class extends self.ISpriteInstance {},
	spr_start_ball_pos: class extends self.ISpriteInstance {},
	spr_node_ball_send: class extends self.ISpriteInstance {},
	spr_node_type_cng: class extends self.ISpriteInstance {},
	spr_ball_node_sound: class extends self.ISpriteInstance {},
	spr_ball_count_text: class extends self.ITextInstance {},
	spr_score_text: class extends self.ITextInstance {},
	spr_game_over_text: class extends self.ITextInstance {},
	spr_game_over_score_text: class extends self.ITextInstance {},
	spr_back_btn: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	spr_reload_btn: class extends self.ISpriteInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	spr_ball_container: class extends self.ISpriteInstance {},
	spr_ball_container2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	spr_door_bar: class extends self.ISpriteInstance {},
	spr_ball: class extends self.ISpriteInstance {},
	spr_hole_container: class extends self.ISpriteInstance {},
	spr_holes: class extends self.ISpriteInstance {},
	spr_glass: class extends self.ISpriteInstance {},
	spr_air_flow: class extends self.IParticlesInstance {},
	tapToPlay: class extends self.ITiledBackgroundInstance {},
	spr_ball_ramin: class extends self.ISpriteInstance {},
	spr_node_game_over: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	spr_node_ball_shake: class extends self.ISpriteInstance {}
}