{
	"version": 1504599313,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/pot-sheet0.png",
		"images/beekiri-sheet0.png",
		"images/beekiri-sheet1.png",
		"images/buukiri-sheet0.png",
		"images/buukiri-sheet1.png",
		"images/buukiri-sheet2.png",
		"images/sari-sheet0.png",
		"images/beekanan-sheet0.png",
		"images/beekanan-sheet1.png",
		"images/buukanan-sheet0.png",
		"images/buukanan-sheet1.png",
		"images/buukanan-sheet2.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/coin-sheet2.png",
		"images/ledak-sheet0.png",
		"images/ledak-sheet1.png",
		"images/coinjalan-sheet0.png",
		"images/daun-sheet0.png",
		"images/daun-sheet1.png",
		"images/tghbunga-sheet0.png",
		"images/butbomb-sheet0.png",
		"images/butbomb-sheet1.png",
		"images/ledakbomb-sheet0.png",
		"images/pusatbom-sheet0.png",
		"images/flash-sheet0.png",
		"images/bgresult-sheet0.png",
		"images/buthome-sheet0.png",
		"images/butretry-sheet0.png",
		"images/bgopening-sheet0.png",
		"images/butopening-sheet0.png",
		"images/backtoweb-sheet0.png",
		"images/mute_sound-sheet0.png",
		"images/mute_sound-sheet1.png",
		"media/cancel - 2.m4a",
		"media/cancel - 2.ogg",
		"media/8 bit ricochet.m4a",
		"media/8 bit ricochet.ogg",
		"media/explosion 3.m4a",
		"media/explosion 3.ogg",
		"media/menu click 2.m4a",
		"media/menu click 2.ogg",
		"media/ok - 3.m4a",
		"media/ok - 3.ogg",
		"media/mattoglseby - 2.m4a",
		"media/mattoglseby - 2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"txtgameid.txt"
	]
}