const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Particles,
		C3.Behaviors.destroy,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{DestroyOutside: 0},
	{spr_effect_particle_black: 0},
	{spr_effect_particle_white: 0},
	{color: 0},
	{Solid: 0},
	{spr_ball_white: 0},
	{type: 0},
	{Tween: 0},
	{spr_ball_black: 0},
	{text_game_title_two: 0},
	{text_game_title_dots: 0},
	{spr_play_btn: 0},
	{Touch: 0},
	{Anchor: 0},
	{Obstacle: 0},
	{txt_score: 0},
	{text_tap_to_play: 0},
	{Audio: 0},
	{Ball: 0},
	{trigger: 0},
	{UP_BALL_LIMIT_Y: 0},
	{DOWN_BALL_LIMIT_Y: 0},
	{Score: 0},
	{swapTimeInSec: 0},
	{distanceCngTimmer: 0},
	{randomColorPick: 0},
	{setScore: 0}
];

self.InstanceType = {
	spr_effect_particle_black: class extends self.IParticlesInstance {},
	spr_effect_particle_white: class extends self.IParticlesInstance {},
	spr_ball_white: class extends self.ISpriteInstance {},
	spr_ball_black: class extends self.ISpriteInstance {},
	text_game_title_two: class extends self.ITextInstance {},
	text_game_title_dots: class extends self.ITextInstance {},
	spr_play_btn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Anchor: class extends self.ISpriteInstance {},
	Obstacle: class extends self.ISpriteInstance {},
	txt_score: class extends self.ITextInstance {},
	text_tap_to_play: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Ball: class extends self.ISpriteInstance {}
}