const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Arr.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{Array: 0},
	{cupPositions: 0},
	{cupSequence: 0},
	{slotStatus: 0},
	{trayTypes: 0},
	{traySlots: 0},
	{cupPositionsWithSeq: 0},
	{UI: 0},
	{hand: 0},
	{stackIndex: 0},
	{slotIndex: 0},
	{cupCount: 0},
	{isPlaced: 0},
	{SET_UID: 0},
	{isActive: 0},
	{tray_animation: 0},
	{Find_Duplicate: 0},
	{Navy_Blue: 0},
	{Pink: 0},
	{Sky_Blue: 0},
	{tap: 0},
	{AJAX: 0},
	{pick_cup: 0},
	{spr_trigger: 0},
	{pathIndex: 0},
	{target_tray: 0},
	{isDestroy: 0},
	{main_cup: 0},
	{Tween: 0},
	{MoveTo: 0},
	{CupFamily: 0},
	{TrayFamily: 0},
	{isTriger: 0},
	{SelectedTrayUID: 0},
	{SLOT_1: 0},
	{SLOT_2: 0},
	{SLOT_3: 0},
	{ActiveTrayCount: 0},
	{SLOT_4: 0},
	{stackX: 0},
	{stackY: 0},
	{trayTypeIndex: 0},
	{trayTypeName: 0},
	{trayAmount: 0},
	{choice_cup: 0},
	{TargetTray: 0},
	{array_flag: 0},
	{x: 0},
	{y: 0},
	{cup_name: 0}
];

self.InstanceType = {
	Array: class extends self.IArrayInstance {},
	cupPositions: class extends self.IArrayInstance {},
	cupSequence: class extends self.IArrayInstance {},
	slotStatus: class extends self.IArrayInstance {},
	trayTypes: class extends self.IArrayInstance {},
	traySlots: class extends self.IArrayInstance {},
	cupPositionsWithSeq: class extends self.IArrayInstance {},
	UI: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	Navy_Blue: class extends self.ISpriteInstance {},
	Pink: class extends self.ISpriteInstance {},
	Sky_Blue: class extends self.ISpriteInstance {},
	tap: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	spr_trigger: class extends self.ISpriteInstance {},
	main_cup: class extends self.ISpriteInstance {},
	CupFamily: class extends self.ISpriteInstance {},
	TrayFamily: class extends self.ISpriteInstance {}
}