const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.MoveTo,
		C3.Behaviors.jumpthru,
		C3.Plugins.TiledBg,
		C3.Behaviors.wrap,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetX
	];
};
self.C3_JsPropNameTable = [
	{spr_car: 0},
	{Tween: 0},
	{spr_ui: 0},
	{spr_demo: 0},
	{spr_water_old: 0},
	{spr_bg: 0},
	{ScrollTo: 0},
	{spr_player: 0},
	{Keyboard: 0},
	{Solid: 0},
	{wook_sold: 0},
	{wook_sold_activator: 0},
	{spr_power_bar: 0},
	{spr_power_bar_container: 0},
	{MoveTo: 0},
	{Jumpthru: 0},
	{spr_wood: 0},
	{spr_target_wood_node: 0},
	{spr_spwn_wood_node: 0},
	{Wrap: 0},
	{spr_water: 0},
	{spr_moving_stop_node: 0},
	{HoldTime: 0},
	{IsJumping: 0},
	{isMoving: 0}
];

self.InstanceType = {
	spr_car: class extends self.ISpriteInstance {},
	spr_ui: class extends self.ISpriteInstance {},
	spr_demo: class extends self.ISpriteInstance {},
	spr_water_old: class extends self.ISpriteInstance {},
	spr_bg: class extends self.ISpriteInstance {},
	spr_player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	wook_sold: class extends self.ISpriteInstance {},
	wook_sold_activator: class extends self.ISpriteInstance {},
	spr_power_bar: class extends self.ISpriteInstance {},
	spr_power_bar_container: class extends self.ISpriteInstance {},
	spr_wood: class extends self.ISpriteInstance {},
	spr_target_wood_node: class extends self.ISpriteInstance {},
	spr_spwn_wood_node: class extends self.ISpriteInstance {},
	spr_water: class extends self.ITiledBackgroundInstance {},
	spr_moving_stop_node: class extends self.ISpriteInstance {}
}