const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Behaviors.jumpthru,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Platform: 0},
	{spr_player: 0},
	{spr_power: 0},
	{Touch: 0},
	{id: 0},
	{Jumpthru: 0},
	{spr_platfom: 0},
	{spr_spwn_wall: 0},
	{spr_destory_wall: 0},
	{ui_collections: 0},
	{BG: 0},
	{Solid: 0},
	{spr_damage: 0},
	{spr_cloud: 0},
	{IsCharging: 0},
	{JumpPower: 0},
	{MaxPower: 0},
	{ChargeSpeed: 0},
	{isFloorPlayer: 0},
	{defaultPosX: 0},
	{defaultPosY: 0},
	{jumpPosX: 0},
	{jumpPosY: 0},
	{swapPosition: 0}
];

self.InstanceType = {
	spr_player: class extends self.ISpriteInstance {},
	spr_power: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	spr_platfom: class extends self.ISpriteInstance {},
	spr_spwn_wall: class extends self.ISpriteInstance {},
	spr_destory_wall: class extends self.ISpriteInstance {},
	ui_collections: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	spr_damage: class extends self.ISpriteInstance {},
	spr_cloud: class extends self.ISpriteInstance {}
}