const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Tilemap,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.AbsoluteX,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Pin.Acts.SetDestroy
	];
};
self.C3_JsPropNameTable = [
	{spr_road: 0},
	{spr_road_gress: 0},
	{spr_road_parking: 0},
	{spr_gate: 0},
	{id: 0},
	{spr_arrows: 0},
	{Tween: 0},
	{spr_trans: 0},
	{spr_trans_pointer: 0},
	{tile_bg: 0},
	{spr_level_bg: 0},
	{Sine: 0},
	{spr_game_title_bg: 0},
	{spr_level_text_bg: 0},
	{spr_deco_objects: 0},
	{spr_hud_all: 0},
	{spr_game_over_transtition: 0},
	{outY: 0},
	{in: 0},
	{spr_cancel_btn_popup: 0},
	{spr_setting_popup: 0},
	{spr_coming_soon: 0},
	{text_coming_soon: 0},
	{spr_btn_check: 0},
	{spr_btn_cancel: 0},
	{spr_btn_back: 0},
	{spr_btn_setting: 0},
	{spr_btn_cancel_setting: 0},
	{spr_sound_btn: 0},
	{spr_reset_level_btn: 0},
	{spr_artboard_level_title: 0},
	{level: 0},
	{spr_artboard_level_choice: 0},
	{spr_tap_to_start: 0},
	{text_level_choice_number: 0},
	{spr_level_text: 0},
	{spr_timer_text: 0},
	{spr_cancel_btn_text: 0},
	{spr_sound_setting_text: 0},
	{spr_level_reset_setting_text: 0},
	{Browser: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{spr_car_blast: 0},
	{spr_car_smoke_item: 0},
	{Pin: 0},
	{spr_smoke_particels: 0},
	{spr_destory_particels: 0},
	{Solid: 0},
	{spr_red_car_1: 0},
	{speed: 0},
	{move_angle: 0},
	{every_second: 0},
	{car__animation_frame: 0},
	{steps: 0},
	{spr_spwn_enemy_car_1: 0},
	{step_count: 0},
	{Bullet: 0},
	{spr_enime_car_runner_1: 0},
	{spr_destory_enemy: 0},
	{spr_spwn_enemy_car_2: 0},
	{spr_red_car_2: 0},
	{spr_enime_car_runner_2: 0},
	{target: 0},
	{spr_car: 0},
	{spr_car_runner: 0},
	{spr_turn_car: 0},
	{isActive: 0},
	{spr_turing: 0},
	{spr_turn_anime_car: 0},
	{is_show: 0},
	{spr_info_close_btn: 0},
	{spr_level_part_achivment: 0},
	{ScrollTo: 0},
	{MoveTo: 0},
	{spr_move_level: 0},
	{spr_level_achivment: 0},
	{spr_transition: 0},
	{spr_start_game_transparent_bg: 0},
	{Audio: 0},
	{SELECTED_LEVEL: 0},
	{isRestLevel: 0},
	{SET_LEVEL: 0},
	{Total_CARS: 0},
	{GET__CURRENT_LEVEL_NUMBER: 0},
	{isCreate: 0},
	{Level_Dragging: 0},
	{Level_DragStartX: 0},
	{Level_DragScrollX: 0},
	{gameLevel: 0},
	{direction: 0},
	{RED_CAR_DICRETION: 0},
	{RED_CAR_DICRETION_2: 0}
];

self.InstanceType = {
	spr_road: class extends self.ISpriteInstance {},
	spr_road_gress: class extends self.ISpriteInstance {},
	spr_road_parking: class extends self.ISpriteInstance {},
	spr_gate: class extends self.ISpriteInstance {},
	spr_arrows: class extends self.ISpriteInstance {},
	spr_trans: class extends self.ISpriteInstance {},
	spr_trans_pointer: class extends self.ISpriteInstance {},
	tile_bg: class extends self.ITilemapInstance {},
	spr_level_bg: class extends self.ISpriteInstance {},
	spr_game_title_bg: class extends self.ISpriteInstance {},
	spr_level_text_bg: class extends self.ISpriteInstance {},
	spr_deco_objects: class extends self.ISpriteInstance {},
	spr_hud_all: class extends self.ISpriteInstance {},
	spr_game_over_transtition: class extends self.ISpriteInstance {},
	spr_cancel_btn_popup: class extends self.ISpriteInstance {},
	spr_setting_popup: class extends self.ISpriteInstance {},
	spr_coming_soon: class extends self.ISpriteInstance {},
	text_coming_soon: class extends self.ITextInstance {},
	spr_btn_check: class extends self.ISpriteInstance {},
	spr_btn_cancel: class extends self.ISpriteInstance {},
	spr_btn_back: class extends self.ISpriteInstance {},
	spr_btn_setting: class extends self.ISpriteInstance {},
	spr_btn_cancel_setting: class extends self.ISpriteInstance {},
	spr_sound_btn: class extends self.ISpriteInstance {},
	spr_reset_level_btn: class extends self.ISpriteInstance {},
	spr_artboard_level_title: class extends self.ISpriteInstance {},
	spr_artboard_level_choice: class extends self.ISpriteInstance {},
	spr_tap_to_start: class extends self.ISpriteInstance {},
	text_level_choice_number: class extends self.ITextInstance {},
	spr_level_text: class extends self.ITextInstance {},
	spr_timer_text: class extends self.ITextInstance {},
	spr_cancel_btn_text: class extends self.ITextInstance {},
	spr_sound_setting_text: class extends self.ITextInstance {},
	spr_level_reset_setting_text: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	spr_car_blast: class extends self.ISpriteInstance {},
	spr_car_smoke_item: class extends self.ISpriteInstance {},
	spr_smoke_particels: class extends self.IParticlesInstance {},
	spr_destory_particels: class extends self.IParticlesInstance {},
	spr_red_car_1: class extends self.ISpriteInstance {},
	spr_spwn_enemy_car_1: class extends self.ISpriteInstance {},
	spr_enime_car_runner_1: class extends self.ISpriteInstance {},
	spr_destory_enemy: class extends self.ISpriteInstance {},
	spr_spwn_enemy_car_2: class extends self.ISpriteInstance {},
	spr_red_car_2: class extends self.ISpriteInstance {},
	spr_enime_car_runner_2: class extends self.ISpriteInstance {},
	spr_car: class extends self.ISpriteInstance {},
	spr_car_runner: class extends self.ISpriteInstance {},
	spr_turn_car: class extends self.ISpriteInstance {},
	spr_turing: class extends self.ISpriteInstance {},
	spr_turn_anime_car: class extends self.ISpriteInstance {},
	spr_info_close_btn: class extends self.ISpriteInstance {},
	spr_level_part_achivment: class extends self.ISpriteInstance {},
	spr_move_level: class extends self.ISpriteInstance {},
	spr_level_achivment: class extends self.ISpriteInstance {},
	spr_transition: class extends self.ISpriteInstance {},
	spr_start_game_transparent_bg: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}