const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{txt_timer: 0},
	{txt_score: 0},
	{bg: 0},
	{item: 0},
	{isSelected: 0},
	{Platform: 0},
	{Solid: 0},
	{MoveTo: 0},
	{Box: 0},
	{Pin: 0},
	{spr_item: 0},
	{isActive: 0},
	{spr_connect: 0},
	{Touch: 0},
	{ArraySelectedBox: 0},
	{spr_node_solid: 0},
	{Physics: 0},
	{DestroyOutside: 0},
	{spr_item_destroy: 0},
	{spr_node: 0},
	{ID_: 0},
	{createCount: 0},
	{spr_node_spwaner: 0},
	{HUD: 0},
	{ui_collections2: 0},
	{selectedItem: 0},
	{connecteditems: 0},
	{timer: 0},
	{score: 0},
	{randomItem: 0},
	{ItemX: 0},
	{ItemY: 0}
];

self.InstanceType = {
	txt_timer: class extends self.ITextInstance {},
	txt_score: class extends self.ITextInstance {},
	bg: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	spr_item: class extends self.ISpriteInstance {},
	spr_connect: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	ArraySelectedBox: class extends self.IArrayInstance {},
	spr_node_solid: class extends self.ISpriteInstance {},
	spr_item_destroy: class extends self.ISpriteInstance {},
	spr_node: class extends self.ISpriteInstance {},
	spr_node_spwaner: class extends self.ISpriteInstance {},
	HUD: class extends self.ISpriteInstance {},
	ui_collections2: class extends self.ISpriteInstance {}
}